---
ID: "3cf80da6-23da-4b53-ab2d-43bc78d1cef1"
Parent: "8c5ac25d-bf52-4b79-9d79-3faec6c2deff"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/play-stores/play-netherlands/Presentation/Headless Variants/LinkList/Default"
BranchID: "70519928-c595-4b2b-bb35-75022feecc4c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{25F1A8E5-EB4C-4202-A9F7-A97DB52DA9AF}"
Languages:
- Language: "nl-NL"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a190de3d-b0ba-461f-83f8-df137ed2a9dd"
