---
ID: "6e38c19a-2b15-4eb2-a9cd-3a678d22adde"
Parent: "3c84cc03-c70b-4fee-9e0a-ab4513404522"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/play-stores/play-uk/Presentation/Headless Variants/Promo/Default"
BranchID: "37229eac-e94c-4507-b543-6cb1f31294e4"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C8F0AA39-7D5A-4BD2-9452-C21B3BFED25D}"
Languages:
- Language: "en-GB"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1e95ded4-d1ac-4ebe-82ca-bc5f3dd35f99"
