---
ID: "270eafe0-0740-44da-bdb6-9a7dc026fea7"
Parent: "a56a682b-ca2f-4e3b-883a-3090bbeda2c4"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/play-nutrition/nutrilife/Presentation/Headless Variants/PageContent/Default"
BranchID: "5abe3762-5a9c-4710-9730-bb302e90fd13"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E9B59BC9-57CB-43AC-8FD7-F9A676B0C46F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "396bf6d5-46e6-4060-ace5-4bac69dc5cfd"
