---
ID: "f8d61f6f-2f3d-4d49-bc0a-de8fa280b60f"
Parent: "21aec3a6-e701-4c96-b1ea-856ba42dfb6f"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/play-stores/play-portugal/Presentation/Headless Variants/Navigation/Default"
BranchID: "70519928-c595-4b2b-bb35-75022feecc4c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{25F1A8E5-EB4C-4202-A9F7-A97DB52DA9AF}"
Languages:
- Language: "pt-PT"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33c2a652-b019-4546-90d1-8aa8d4d7e63f"
